_target_: models.boosting.LightGBMTrainer

params:
  boosting_type: gbdt
  objective: binary
  metric: auc
  learning_rate: 0.05
  bagging_seed: 42
  num_leaves: 128
  max_depth: -1
  min_child_weight: 0.03
  bagging_fraction: 0.8
  feature_fraction: 0.8
  lambda_l1: 0.04
  lambda_l2: 0.06
  num_threads: -1

model_path: resource/models/
results: 5fold-lightgbm-baseline
early_stopping_rounds: 100
num_boost_round: 2000
verbose_eval: 100
seed: 42
n_splits: 5