_target_: models.mlp.DeepTrainer

results: 5fold-mlp-baseline
model_path: resource/models/

params: {}

# Model architecture
hidden_dims: 
 - 128
 - 64
 - 32

embedding_dim: 8
dropout: 0.3

cat_feature_sizes:
  - 5
  - 4
  - 5
  - 4

# Training params
lr: 0.001
epochs: 10
batch_size: 64
device: cuda

# CV params
n_splits: 5
seed: 42

